services:
  - type: web
    name: spamshare
    env: python
    plan: free
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers=1 --reuse-port main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true